spring:
  application:
    name: booking-service

  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:configserver:"

  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
      discovery:
        enabled: true
        service-id: config-server

  profiles:
    include: kafka

# 예매 입장, 세션 토큰 -> 추후 컨피그 서버로 옮길 예정
booking:
  token:
    entry-secret:
    session-secret:
    session-token-validity:
