name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER: ${{ secrets.GH_USER }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 테스트 → 문서 생성 → 최종 빌드 (REST Docs 포함)
      - name: Build (test → asciidoctor → bootJar)
        run: ./gradlew test asciidoctor bootJar
